### ISSUE TITLE
Empty table

### ISSUE THREAD

**Issue by quiquelhappy** [Taronyuu/MinecraftStatistics#6]
Hello!
The plugin is still creating all the stat types on 1.18 (well done, ur code is solid). Sadly, stats are not being pushed to the database, so the table is always empty, even tho the columns are created correctly.

![image](https://user-images.githubusercontent.com/12534357/144388585-a156ccdf-955c-48cf-a221-9b0ffe83cd27.png)

**Comment by quiquelhappy** [comment]
```
[08:48:05 WARN]: java.sql.SQLException: Operation not allowed for a result set of type ResultSet.TYPE_FORWARD_ONLY.
[08:48:05 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
[08:48:05 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[08:48:05 WARN]:        at com.mysql.cj.jdbc.result.ResultSetImpl.last(ResultSetImpl.java:1752)
[08:48:05 WARN]:        at minecraftstatistics.jar//nl.zandervdm.minecraftstatistics.Tasks.CreatePlayerOnlineTask.run(CreatePlayerOnlineTask.java:27)
[08:48:05 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[08:48:05 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[08:48:05 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[08:48:05 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[08:48:05 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[08:48:05 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by JorisvD01** [comment]
Same issue ^

**Comment by JorisvD01** [comment]
> ```
> [08:48:05 WARN]: java.sql.SQLException: Operation not allowed for a result set of type ResultSet.TYPE_FORWARD_ONLY.
> [08:48:05 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
> [08:48:05 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
> [08:48:05 WARN]:        at com.mysql.cj.jdbc.result.ResultSetImpl.last(ResultSetImpl.java:1752)
> [08:48:05 WARN]:        at minecraftstatistics.jar//nl.zandervdm.minecraftstatistics.Tasks.CreatePlayerOnlineTask.run(CreatePlayerOnlineTask.java:27)
> [08:48:05 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
> [08:48:05 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
> [08:48:05 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
> [08:48:05 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> [08:48:05 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> [08:48:05 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
> ```

Did you fix this yet? I'm having the same issue
